name: Basic CI

on: [push]

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "✅ GitHub Actions is working!"

