name: Auto-fix ModSecurity Config

on:
  push:
    paths:
      - '**/modsecurity.conf'

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Auto-fix SecRuleEngine to 'On'
        run: |
          FILE=$(find . -name "modsecurity.conf")
          if grep -q "SecRuleEngine Off" "$FILE"; then
            echo "Fixing SecRuleEngine Off → On"
            sed -i 's/SecRuleEngine Off/SecRuleEngine On/' "$FILE"
            git config --global user.email "actions@github.com"
            git config --global user.name "github-actions"
            git commit -am "Auto-fix: Enable SecRuleEngine"
            git push
          else
            echo "No fix needed."
          fi

