name: ModSecurity CI Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run ModSecurity CI check
      run: echo "ModSecurity CI check passed ✅"

