name: Python ModSecurity Check

on:
  push:
    paths:
      - 'modsecurity-check.py'
      - 'modsecurity.conf'

jobs:
  run-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Python script to validate modsecurity.conf
        run: |
          python3 modsecurity-check.py

